### ISSUE TITLE
Can't edit donations

### ISSUE THREAD

**Issue by bausmeier** [jembi/bsis#310]
Trying to save a donation after editing it from the front end gives the following:

```
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "expiryIntervalMinutes" (class model.producttype.ProductType)
```

Also it returns a 502 status which is strange. I think it should be 400.

**Comment by bausmeier** [comment]
The donation has a pack type which in turn has a product type. The endpoint seems to return the entire object for the nested pack type and product type. I would think that they should be view models instead.

**Comment by bausmeier** [comment]
I annotated the `getExpiryIntervalMinutes` with `@JsonIgnore` (there don't seem to be any uses of `expiryIntervalMinutes` on the front end) which resolves the first error, but now I see:

```
java.text.ParseException: Unparseable date: "1970-01-01T12:06:05Z"
	at java.text.DateFormat.parse(DateFormat.java:357)
	at utils.CustomDateFormatter.getTimeFromString(CustomDateFormatter.java:52)
	at backingform.CollectedSampleBackingForm.setBleedStartTime(CollectedSampleBackingForm.java:108)
	...
```

@debonair Could this be related to your date format changes?
