### ISSUE TITLE
Fix issue causing respository tests to fail

### ISSUE THREAD

**Issue by timler** [jembi/bsis#359]
There is currently an issue with some repository tests failing depending on the order the tests are executed in. 

This appears to affect local machines but not Travis and specifically these tests

 * AdverseEventRepositoryTests
 * ComponentRepositoryTests
 * DonationBatchRepositoryTests
 * PostDonationCounsellingRepositoryTests

**Comment by timler** [comment]
Exception seen in AdverseEventRepositoryTests  was:

```
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: foreign key no parent; FK_K8UIGMKEII4Q8WCAD9BJLV14 table: DONOR
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:147)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	... 76 more
Caused by: org.hsqldb.HsqlException: integrity constraint violation: foreign key no parent; FK_K8UIGMKEII4Q8WCAD9BJLV14 table: DONOR
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Constraint.getException(Unknown Source)
	at org.hsqldb.Constraint.checkInsert(Unknown Source)
	at org.hsqldb.StatementDML.performIntegrityChecks(Unknown Source)
	at org.hsqldb.StatementDML.insertRowSet(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 80 more
```

**Comment by timler** [comment]
Other related PRs and issues are:

 * https://github.com/jembi/bsis/pull/332
 * https://github.com/jembi/bsis/pull/341
 * https://github.com/jembi/bsis/issues/340

**Comment by timler** [comment]
So to conclude, it is unclear why setting the Authentication object in the Spring SecurityContext would cause this issue. When the ComponentRespositoryTest is finished the database should be returned to its previous state (using a rollback provided by the Spring Test framework) and the DBUnit DELETE_ALL DatabaseOperation. However it appears that the User associated with the Authentication object is not actually deleted from the database and DBUnit doesn't throw an error as we would expect it to.
